[include]
files = [
  "/usr/local/share/umbriel/effects/animation/squash/effect.toml",
  "/usr/local/share/umbriel/effects/animation/portal/effect.toml",
  "/usr/local/share/umbriel/effects/border/pulse/effect.toml",
  "/usr/local/share/umbriel/effects/screen/vignette/effect.toml",
  "src/general.toml",
  "src/animations.toml",
  "src/appearance.toml",
  "src/input.toml",
  "src/keybinds.toml",
  "src/rules.toml",
  ]

[include.optional]
files = ["noctalia.toml"]
