[colors]
background = "#c8aeb9FF"
text_primary = "#000000FF"
text_muted = "#52504aFF"
accent_primary = "#cc7e8bFF"
accent_secondary = "#000000FF"
warning = "#d4a2acFF"
error = "#964860FF"
insert_hint = "#d4a2ac80"
backdrop = "#c8aeb9FF"

[colors.border]
focused = "#cc7e8bFF"
unfocused = "#c8aeb9FF"
scratchpad_focused = "#d4a2acFF"
scratchpad_unfocused = "#e4cdd2FF"
outer = "#dac6c8FF"

[colors.overview]
background_tint = "#dac6c888"
badge = "#cc7e8bFF"
workspace_background = "#dac6c8FF"
