[colors]
background = "#292929FF"
text_primary = "#c2c2c2FF"
text_muted = "#929292FF"
accent_primary = "#cc7e8bFF"
accent_secondary = "#c9afbaFF"
warning = "#d4a2acFF"
error = "#a05b71FF"
insert_hint = "#d4a2ac80"
backdrop = "#292929FF"

[colors.border]
focused = "#cc7e8bFF"
unfocused = "#292929FF"
outer = "#232323FF"

[colors.overview]
background_tint = "#23232388"
badge = "#cc7e8bFF"
workspace_background = "#232323FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#d4a2acFF"
border_color_unfocused = "#8f3547FF"
