[animation]
enabled = true
# duration_ms = 200
# curve = "snappy"

[animation.windows_in]
enabled = true
duration_ms = 350
effect = "portal"
curve = "linear"
style = "none"         # "popin", "zoom", "slide", "fade", or "none"
# scale = 0.1          # 0.1-1.0, used by "popin"

[animation.windows_out]
enabled = true
duration_ms = 350
effect = "portal"
curve = "linear"
# style = "fade"        # "fade" or "slide"

[animation.windows_move]
enabled = true
duration_ms = 150
curve = "linear"
effect = "squash"

[animation.workspaces]
enabled = true
duration_ms = 150
curve = "linear"

[animation.scratchpad]
enabled = true
duration_ms = 350
curve = "ease"
dim = 0.5             # 0.0-1.0
blur = true           # requires appearance.blur.enabled
scale = 0.6667        # 0 preserves geometry; 0.1-1.0 sizes and centers on entry
maximize = false      # maximize to edges on entry
fullscreen = false    # fullscreen on entry

[animation.border]
enabled = true
duration_ms = 500
curve = "ease"

[animation.dim_unfocused]
enabled = true
duration_ms = 500
curve = "easeout"
dim = 0.075             # 0.0-1.0

[animation.layers]
enabled = true
duration_ms = 250
curve = "ease"

[animation.springs]
sprangs =  { damping = 0.65, stiffness = 1000 }
