[general]
autostart = [
	"dbus-update-activation-environment --all",
  	"noctalia --daemon",
  	"kitty -1 --start-as=hidden &",
	"mpd &",
  	"pipewire &",
  	"pipewire-pulse &",
	"wl-clip-persist -c both &",
  	"~/.scripts/./autostart &",
	"~/.scripts/./rpc-checker &"
]

xwayland = false
show_cheatsheet = false
focus_on_activate = false
honor_restored_maximize = false

[environment]
DESKTOP_SHELL = "noctalia"