[input]
middle_click_paste = false

[input.keyboard]
layout = ""
variant = ""
options = "caps:swapescape,shift:both_capslock_cancel"
repeat_rate = 40               # 0-1000 Hz
repeat_delay = 300             # 0-10000 ms

[input.touchpad]
tap = true
natural_scroll = true
accel_profile = "adaptive"
sensitivity = 0.5
scroll_factor = 3.0
disable_while_typing = true

[input.mouse]
accel_profile = "flat"
sensitivity = 0.0
scroll_wheel_step = 60

[input.tablet]
enabled = false

[input.cursor]
theme = "Bibata-Gruvbox"
size = 32
follows_focus = true
hardware_cursor = true
hide_when_typing = true
hide_timeout_ms = 0

[input.focus]
follows_mouse = false