[keybinds]

# Applications

"Mod+M" = "spawn:sone"
"Mod+W" = "spawn:whisp"
"Mod+Z" = "spawn:foot yazi"
"Mod+Return" = "spawn:kitty -1"
"Mod+Semicolon" = "spawn:hyprpicker -a -c"
"Mod+E" = "spawn:wlrctl window focus title:meow"
"Mod+R" = "spawn:wlrctl window focus title:rmpc"
"Mod+D" = "spawn:wlrctl window focus title:concord"
"Mod+B" = "spawn:wlrctl window focus helium || helium &"
"Mod+Shift+B" = "spawn:wlrctl window focus zen-default || zen &"

"Mod+Backslash" = "scratchpad-toggle"
"Mod+Shift+Backslash" = "scratchpad-focus-next"
"Mod+Bracketright" = "window-move-to-scratchpad"
"Mod+Bracketleft" = "window-restore-from-scratchpad"

# Noctalia msg actions

"Mod+S" = "spawn:noctalia msg screenshot-region"
"Mod+Ctrl+S" = "spawn:noctalia msg screenshot-fullscreen"

"Mod+Shift+S" = "spawn:noctalia msg settings-toggle"
"Mod+Shift+D" = "spawn:noctalia msg theme-mode-toggle"
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Shift+Escape" = "spawn:noctalia msg panel-toggle session"
"Mod+Shift+C" = "spawn:noctalia msg panel-toggle control-center"
"Mod+Shift+V" = "spawn:noctalia msg panel-toggle panel-toggle clipboard"
"Mod+Shift+N" = "spawn:noctalia msg panel-toggle control-center notifications"
"Mod+Ctrl+R" = "spawn:noctalia msg plugin noctalia/screen_recorder:service all toggle portal"
"Mod+Shift+R" = "spawn:noctalia msg plugin noctalia/screen_recorder:service all toggle focused"

# Media and brightness

XF86AudioNext = "spawn:playerctl next"
XF86AudioPrev = "spawn:playerctl previous"
XF86AudioPlay = "spawn:playerctl play-pause"

XF86AudioMute = "spawn:noctalia msg volume-mute"
XF86AudioRaiseVolume = "spawn:noctalia msg volume-up 5"
XF86AudioLowerVolume = "spawn:noctalia msg volume-down 5"

XF86MonBrightnessUp = "spawn:noctalia msg brightness-up"
XF86MonBrightnessDown = "spawn:noctalia msg brightness-down"
XF86KbdBrightnessUp = "spawn:noctalia msg keyboard-backlight-up"
XF86KbdBrightnessDown = "spawn:noctalia msg keyboard-backlight-down"

# Workspace and window actions

"Mod+Shift+Q" = "window-close"

"Mod+Up" = "window-focus-up"
"Mod+Down" = "window-focus-down"
"Mod+Left" = "window-focus-previous"
"Mod+Right" = "window-focus-next"

"Mod+Comma" = "window-consume-or-expel-left"
"Mod+Period" = "window-consume-or-expel-right"

"Mod+Ctrl+Left" = "column-move-left"
"Mod+Ctrl+Right" = "column-move-right"

"Mod+Shift+Up" = "workspace-previous"
"Mod+Shift+Down" = "workspace-next"

"Mod+Ctrl+Up" = "window-move-to-workspace-previous"
"Mod+Ctrl+Down" = "window-move-to-workspace-next"

"Mod+Minus" = "window-modify-width:-0.1"
"Mod+Equal" = "window-modify-width:+0.1"
"Mod+Shift+Minus" = "window-modify-width:-0.5"
"Mod+Shift+Equal" = "window-modify-width:+0.5"

"Mod+Ctrl+Minus" = "window-modify-height:-0.1"
"Mod+Ctrl+Equal" = "window-modify-height:+0.1"

"Mod+C" = "column-center"
"Mod+Ctrl+C" = "window-center"
"Mod+Ctrl+P" = "window-toggle-pinned"
"Mod+Ctrl+F" = "window-toggle-floating"
"Mod+Alt+F" = "window-focus-switch-floating"

"Mod+Shift+M" = "window-toggle-maximize"
"Mod+Shift+F" = "window-toggle-fullscreen"

"Mod+1" = "workspace-switch:一"
"Mod+2" = "workspace-switch:二"
"Mod+3" = "workspace-switch:三"
"Mod+4" = "workspace-switch:四"
"Mod+5" = "workspace-switch:五"

"Mod+Ctrl+O" = "overview-toggle"
